# Generated by Django 5.0.1 on 2024-02-26 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Human', '0001_ initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='human',
            options={'ordering': ['-is_published'], 'verbose_name': 'Знаменитость', 'verbose_name_plural': 'Знаменитости'},
        ),
        migrations.AlterField(
            model_name='human',
            name='biografia',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='human',
            name='birthdate',
            field=models.DateTimeField(help_text='birthdate', verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='human',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='human',
            name='name_surname',
            field=models.CharField(max_length=150, verbose_name='Кто это'),
        ),
        migrations.AlterField(
            model_name='human',
            name='photo',
            field=models.ImageField(upload_to='media/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='human',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='human',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Human.profession', verbose_name='Профессия'),
        ),
    ]
